sudo: required

language: python

python:
  - "3.6"

env:
  global:
    - COMPOSE_PROJECT_NAME=headless
  matrix:
    - ON_TRAVIS=True
      TASK_ALWAYS_EAGER=True
      HEADLESS_COMMAND=dev
    - ON_TRAVIS=True
      TASK_ALWAYS_EAGER=False
      HEADLESS_COMMAND="coverage run --rcfile=/home/app/.coveragerc /usr/local/bin/celery -A headless.celery_app worker -l info -Q inasafe-headless -n inasafe-headless.%h -P solo"
      WORKER_SCALE=1
      INASAFE_LOG_LEVEL=10 # DEBUG log level
    # Special environment for subsequent run stress testing
    - ON_TRAVIS=True
      TASK_ALWAYS_EAGER=True
      HEADLESS_COMMAND=dev
      SUBSEQUENT_RUN_TESTING=True

services:
  - docker

branches:
  only:
    - develop

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libssl-dev
  - sudo pip install -r REQUIREMENTS-TRAVIS.txt

install:
  # build current docker image
  - pushd deployment
  - cp ansible/development/group_vars/all.travis.yml ansible/development/group_vars/all.yml
  - make setup-ansible ANSIBLE_ARGS="--extra-vars='ansible_sudo_pass=\"\"' --extra-vars='pycharm_version=\"\"' --skip-tags=development"
  - make build
  - make up
  - make status
  - cat docker-compose.override.yml
  - cp -f ../src/headless/celeryconfig_sample.py ../src/headless/celeryconfig.py
  - popd

script:
  - pushd deployment
  - make check-flake8
  - ../src/scripts/start_coverage_unittest_worker.sh
  - ../src/scripts/run_coverage_tests.sh ${PWD} ../src
  - ../src/scripts/stop_coverage_unittest_worker.sh || true
  - popd

after_script:
  # Clean up
  - pushd deployment
  - make down
  - popd

after_success:
  - pushd src
  - ls .coverage*
  - coverage combine
  - cat .coverage
  # Fix path (codecov.yml doesn't work)
  # Replace parent directory to travis directory, because we are running
  # coverage using docker mount
  - sed -i 's/home\/app/home\/travis\/build\/inasafe\/inasafe-headless\/src/g' .coverage
  - codecov
  - popd
