#--------- Generic stuff all our Dockerfiles should start with so we get caching ------------
# Note this base image is based on debian
FROM inasafe/qgis-desktop:2.4
MAINTAINER Rizky Maulana Nugraha<lana.pcfre@gmail.com>

RUN export DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND noninteractive
RUN dpkg-divert --local --rename --add /sbin/initctl

# Use local cached debs from host (saves your bandwidth!)
# Change ip below to that of your apt-cacher-ng host
# Or comment this line out if you do not wish to use caching
ADD 71-apt-cacher-ng /etc/apt/apt.conf.d/71-apt-cacher-ng

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
RUN apt-get -y update
RUN apt-get -y install rpl pwgen git inotify-tools

# This section taken on 2 July 2015 from
# https://docs.docker.com/examples/running_ssh_service/
# Sudo is needed by pycharm when it tries to pip install packages
RUN apt-get update && apt-get install -y openssh-server sudo
RUN mkdir /var/run/sshd
RUN echo 'root:docker' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# Open port 22 as we will be using a remote interpreter from pycharm
EXPOSE 22

# End of cut & paste section

#-------------Application Specific Stuff ----------------------------------------------------
# Install QGIS 2.4, git, xvfb
RUN apt-get -y install git xvfb python-setuptools
RUN easy_install pip==7.1.2
ADD REQUIREMENTS.txt /REQUIREMENTS.txt
RUN pip install -r /REQUIREMENTS.txt

ADD run-script.sh /run-script.sh
RUN chmod +x /run-script.sh
ADD helper_script/* /helper_script/
ADD start-dev.sh /start-dev.sh
ADD dev-bashrc.sh /dev-bashrc.sh

RUN ln -s /home/inasafe/src/inasafe/bin/inasafe /usr/bin/inasafe

# RUN echo "export PYTHONPATH=$PYTHONPATH:/home/inasafe/src/inasafe/" >> /root/.bashrc

RUN echo "source /dev-bashrc.sh" >> /root/.bashrc

WORKDIR /home/inasafe/src/inasafe/

CMD ["/start-dev.sh"]
