---
- name: Setup development environment configuration
  hosts: dev-env
  remote_user: '{{ remote_user }}'
  roles:
    - { role: pycharm, when: use_pycharm, tags: development }
    - docker_compose
    - inasafe
  vars_prompt:
    - name: "ansible_sudo_pass"
      prompt: "Sudo password"
      private: yes
    - name: 'pycharm_version'
      prompt: |
        Choose PyCharm Version, available:
        2016.3
        2017.1
        2017.2
        2017.3
      default: '2017.3'
      private: no
