---
- name: checkout InaSAFE source code
  when: inasafe.custom_path is not defined or inasafe.custom_path == ''
  git:
    repo: '{{ inasafe.repo }}'
    remote: '{{ inasafe.remote }}'
    dest: '{{ project_path }}/inasafe'
    version: '{{ inasafe.version }}'
    depth: '{{ inasafe.depth }}'
    force: no
    update: yes
