---

use_pycharm: no
remote_user: travis
remote_group: travis
project_path: "/home/travis/build/inasafe/inasafe-headless"

interpreters:
  inasafe_headless:
    name: 'InaSAFE Headless Container'
    domain_alias: 'docker-inasafe-headless'
    ssh_port: &inasafe_headless_ssh_port 35107
    pycharm_helpers: /root/.pycharm_helpers
    ipaddress: &inasafe_headless_host_ip 192.168.1.7

inasafe:
  repo: https://github.com/inasafe/inasafe.git
  remote: upstream
  version: inasafe_4
  depth: 1

inasafe_headless_worker:
  command: "${HEADLESS_COMMAND}"
  environment:
    TASK_ALWAYS_EAGER: "${TASK_ALWAYS_EAGER}"
    ON_TRAVIS: "${ON_TRAVIS}"
    COVERAGE_PROCESS_START: /home/app/.coveragerc
    SUBSEQUENT_RUN_TESTING: "${SUBSEQUENT_RUN_TESTING}"

docker_port_forward:
  inasafe_headless:
    # Do not port forward, to allow scaling
    non_ssh: *inasafe_headless_ssh_port

integration_test:
  # Path to inasafe-headless's test data directory
  test_data_path: "/home/travis/build/inasafe/inasafe-headless/src/headless/tasks/test/data/"
  # Path to inasafe-headless's test data directory in the docker container
  mapped_test_data_path: "/home/headless_test/data/"
  # Path to inasafe-headless's output test data directory in the docker container
  mapped_output_data_path: "/home/headless_test/data/result/"

geonode_push:
  enable: False
  user: test_geonode_user
  password: test_geonode_password
  url: http://url_to_geonode_instance
