---

use_pycharm: no
remote_user: travis
remote_group: travis
project_path: "/home/travis/build/inasafe/inasafe-headless"

interpreters:
  inasafe_headless:
    name: 'InaSAFE Headless Container'
    domain_alias: 'docker-inasafe-headless'
    ssh_port: &inasafe_headless_ssh_port 35107
    pycharm_helpers: /root/.pycharm_helpers
    ipaddress: &inasafe_headless_host_ip 192.168.1.7

inasafe:
  repo: https://github.com/inasafe/inasafe.git
  remote: upstream
  version: version-4_4_0
  depth: 1

inasafe_headless_worker:
  command: prod inasafe-headless-worker
  environment:
    task_always_eager: "${TASK_ALWAYS_EAGER}"
    on_travis: "${ON_TRAVIS}"

docker_port_forward:
  inasafe_headless:
    ssh: *inasafe_headless_ssh_port

integration_test:
  # Path to inasafe-headless's test data directory
  test_data_path: "/Users/ismailsunni/dev/python/inasafe-headless/src/headless/tasks/test/data/"
  # Path to inasafe-headless's test data directory in the docker container
  mapped_test_data_path: "/home/headless_test/data/"
  # Path to inasafe-headless's output test data directory in the docker container
  mapped_output_data_path: "/home/headless_test/data/result/"

geonode_push:
  enable: False
  user: test_geonode_user
  password: test_geonode_password
  url: http://url_to_geonode_instance
