

inasafeheadless: &inasafeheadless
  build: docker-prod
  hostname: inasafeheadless
  volumes:
    - ../src:/home/inasafe/src
    - ../hazards:/home/hazards
    - ../exposures:/home/exposures
    - ../aggregations:/home/aggregations
    - ../impacts:/home/impacts
